set search_path TO przychodnia;

INSERT INTO specjalizacja (nazwa) VALUES
('Kardiologia'),
('Dermatologia'),
('Pediatria'),
('Neurologia'),
('Ortopedia'),
('Alergologia'),
('Anestezjologia i intensywna terapia'),
('Angiologia'),
('Audiologia i foniatria'),
('Balneologia i medycyna fizykalna'),
('Chirurgia dziecięca'),
('Chirurgia klatki piersiowej'),
('Chirurgia naczyniowa'),
('Chirurgia ogólna'),
('Chirurgia onkologiczna'),
('Chirurgia plastyczna'),
('Chirurgia szczękowo-twarzowa'),
('Choroby płuc'),
('Choroby płuc dzieci'),
('Choroby wewnętrzne'),
('Choroby zakaźne'),
('Dermatologia i wenerologia'),
('Diabetologia'),
('Diagnostyka laboratoryjna'),
('Endokrynologia'),
('Endokrynologia ginekologiczna i rozrodczość'),
('Endokrynologia i diabetologia dziecięca'),
('Epidemiologia'),
('Farmakologia kliniczna'),
('Gastroenterologia'),
('Gastroenterologia dziecięca'),
('Genetyka kliniczna'),
('Geriatria'),
('Ginekologia onkologiczna'),
('Hematologia'),
('Hipertensjologia'),
('Immunologia kliniczna'),
('Intensywna terapia'),
('Kardiochirurgia'),
('Kardiologia dziecięca'),
('Medycyna lotnicza'),
('Medycyna morska i tropikalna'),
('Medycyna nuklearna'),
('Medycyna paliatywna'),
('Medycyna pracy'),
('Medycyna ratunkowa'),
('Medycyna rodzinna'),
('Medycyna sądowa'),
('Medycyna sportowa'),
('Mikrobiologia lekarska'),
('Nefrologia'),
('Nefrologia dziecięca'),
('Neonatologia'),
('Neurochirurgia'),
('Neurologia dziecięca'),
('Neuropatologia'),
('Okulistyka'),
('Onkologia i hematologia dziecięca'),
('Onkologia kliniczna'),
('Ortopedia i traumatologia narządu ruchu'),
('Otorynolaryngologia'),
('Otorynolaryngologia dziecięca'),
('Patomorfologia'),
('Pediatria metaboliczna'),
('Perinatologia'),
('Położnictwo i ginekologia'),
('Psychiatria'),
('Psychiatria dzieci i młodzieży'),
('Radiologia i diagnostyka obrazowa'),
('Radioterapia onkologiczna'),
('Rehabilitacja medyczna'),
('Reumatologia'),
('Seksuologia'),
('Toksykologia kliniczna'),
('Transfuzjologia kliniczna'),
('Transplantologia kliniczna'),
('Urologia'),
('Urologia dziecięca'),
('Zdrowie publiczne'),
('Chirurgia stomatologiczna'),
('Ortodoncja'),
('Periodontologia'),
('Protetyka stomatologiczna'),
('Stomatologia dziecięca'),
('Stomatologia zachowawcza z endodoncją');

INSERT INTO lek (nazwa, substancja_czynna) VALUES
('Apap', 'Paracetamol'),
('Panadol', 'Paracetamol'),
('Tylenol', 'Paracetamol'),
('Ibupietas', 'Ibuprofen'),
('Ibuprom', 'Ibuprofen'),
('Nurofen', 'Ibuprofen'),
('Aspirin', 'Kwas acetylosalicylowy'),
('Acard', 'Kwas acetylosalicylowy'),
('Polopiryna', 'Metamizol'),
('Dipiryna', 'Metamizol'),
('Afobazol', 'Afobazol'),
('Phenibut', 'Fenibut'),
('Amoxyclav', 'Amoksycylina + Kwas klawulanowy'),
('Augmentin', 'Amoksycylina + Kwas klawulanowy'),
('Ciprofloxacin', 'Cyprofloksacyna'),
('Cipronex', 'Cyprofloksacyna'),
('Omeprazol', 'Omeprazol'),
('Gastrozol', 'Omeprazol'),
('Metformin', 'Metformina'),
('Glucophage', 'Metformina');

INSERT INTO alergia (nazwa, opis) VALUES
('Pyłki roślin', 'Alergeny pochodzące z pyłku różnych roślin powodujące objawy sezonowe'),
('Kurz domowy', 'Mieszanka różnych alergenów domowych wywołująca reakcje alergiczne'),
('Roztocza kurzu domowego', 'Mikroskopijne pajęczaki żyjące w kurzu domowym'),
('Sierść zwierząt', 'Białka znajdujące się na sierści, skórze i w ślinie zwierząt'),
('Lateks', 'Naturalna guma wywołująca reakcje alergiczne przy kontakcie'),
('Orzechy', 'Różne rodzaje orzechów powodujące alergię pokarmową'),
('Jaja', 'Białka jaja kurzego wywołujące reakcje alergiczne'),
('Mleko', 'Białka mleka krowiego powodujące nietolerancję lub alergię'),
('Ryby', 'Białka zawarte w mięsie ryb wywołujące alergie pokarmowe'),
('Skorupiaki', 'Białka w skorupiakach takich jak krewetki, kraby, homary'),
('Leszczyna', 'Pyłek leszczyny powodujący sezonowe objawy alergiczne'),
('Olcha', 'Pyłek olchy wywołujący wczesno-wiosenne alergie'),
('Wiąz', 'Pyłek wiązu powodujący wiosenne objawy alergiczne'),
('Buk', 'Pyłek buka wywołujący późno-wiosenne reakcje alergiczne'),
('Brzoza', 'Pyłek brzozy - jeden z najczęstszych alergenów wiosennych'),
('Topola', 'Pyłek topoli powodujący wiosenne objawy alergiczne'),
('Dąb', 'Pyłek dębu wywołujący późno-wiosenne alergie'),
('Wierzba', 'Pyłek wierzby powodujący wczesno-wiosenne objawy'),
('Jesion', 'Pyłek jesionu wywołujący wiosenne reakcje alergiczne'),
('Grab', 'Pyłek grabu powodujący wiosenne objawy alergiczne'),
('Bez czarny', 'Pyłek bzu czarnego wywołujący późno-wiosenne alergie'),
('Lipa drobnolistna', 'Pyłek lipy powodujący letnie objawy alergiczne'),
('Trawy', 'Pyłek traw wywołujący letnie alergie - najczęstszy alergen letni'),
('Babka lancetowata', 'Pyłek babki wywołujący letnie i jesienne objawy'),
('Pokrzywa', 'Pyłek pokrzywy powodujący letnie reakcje alergiczne'),
('Komosa', 'Pyłek komosy wywołujący jesienne objawy alergiczne'),
('Szczaw', 'Pyłek szczawiu powodujący letnie alergie'),
('Bylica', 'Pyłek bylicy - główny alergen jesienny'),
('Zarodniki pleśni', 'Grzyby pleśniowe powodujące całoroczne objawy alergiczne'),
('Ziarno sezamu', 'Nasiona sezamu wywołujące silne reakcje alergiczne'),
('Ryby i inne owoce morza', 'Szeroka grupa alergenów morskich powodujących alergie pokarmowe'),
('Białko jaj', 'Specyficzne białka jaja wywołujące reakcje alergiczne'),
('Soja', 'Białka soi powodujące alergie pokarmowe'),
('Rośliny strączkowe', 'Grupa roślin obejmująca groch, fasolę, soczewicę'),
('Kukurydza', 'Białka kukurydzy wywołujące alergie pokarmowe'),
('Zboża (gluten)', 'Białka zbóż powodujące celiakię i alergię na gluten'),
('Czekolada', 'Składniki czekolady wywołujące reakcje alergiczne'),
('Owoce cytrusowe', 'Białka i substancje w owocach cytrusowych'),
('Miód', 'Naturalne substancje w miodzie powodujące alergie'),
('Orzeszki ziemne', 'Białka orzeszków ziemnych wywołujące silne reakcje'),
('Migdały', 'Białka migdałów powodujące alergie pokarmowe'),
('Pistacje', 'Białka pistacji wywołujące reakcje alergiczne'),
('Nasiona słonecznika', 'Białka nasion słonecznika powodujące alergie'),
('Nasiona sezamu', 'Białka sezamu wywołujące silne reakcje alergiczne'),
('Cebula', 'Substancje w cebuli powodujące nietolerancję pokarmową'),
('Czosnek', 'Związki siarki w czosnku wywołujące reakcje'),
('Zioła przyprawowe', 'Różne zioła używane jako przyprawy'),
('Przyprawy', 'Szeroka grupa przypraw powodujących alergie kontaktowe i pokarmowe'),
('Roztocza', 'Mikroskopijne pajęczaki wywołujące reakcje alergiczne'),
('Konserwanty', 'Chemiczne substancje konserwujące powodujące alergie'),
('Kosmetyki', 'Składniki kosmetyków wywołujące alergie kontaktowe'),
('Jad pszczół', 'Jad owadów błonkoskrzydłych powodujący reakcje anafilaktyczne');

INSERT INTO badanie (nazwa) VALUES
('Morfologia krwi'),
('Badanie moczu'),
('RTG klatki piersiowej'),
('EKG'),
('USG jamy brzusznej'),
('Lipidogram'),
('Glukoza na czczo'),
('Testy alergiczne'),
('Badanie poziomu hormonów tarczycy'),
('Kolonoskopia'),
('Morfologia krwi obwodowej z płytkami krwi'),
('Morfologia krwi obwodowej z wzorem odsetkowym i płytkami krwi'),
('Retikulocyty'),
('Odczyn opadania krwinek czerwonych (OB)'),
('Sód'),
('Potas'),
('Wapń zjonizowany'),
('Żelazo'),
('Żelazo – całkowita zdolność wiązania (TIBC)'),
('Stężenie transferryny'),
('Stężenie hemoglobiny glikowanej (HbAlc)'),
('Mocznik'),
('Kreatynina'),
('Glukoza'),
('Test obciążenia glukozą'),
('Białko całkowite'),
('Proteinogram'),
('Albumina'),
('Białko C-reaktywne (CRP)'),
('Kwas moczowy'),
('Cholesterol całkowity'),
('Cholesterol-HDL'),
('Cholesterol-LDL'),
('Trójglicerydy (TG)'),
('Bilirubina całkowita'),
('Bilirubina bezpośrednia'),
('Fosfataza alkaliczna (ALP)'),
('Aminotransferaza asparaginianowa (AST)'),
('Aminotransferaza alaninowa (ALT)'),
('Gammaglutamylotranspeptydaza (GGTP)'),
('Amylaza'),
('Kinaza kreatynowa (CK)'),
('Fosfataza kwaśna całkowita (ACP)'),
('Czynnik reumatoidalny (RF)'),
('Miano antystreptolizyn O (ASO)'),
('Hormon tyreotropowy (TSH)'),
('Antygen HBs-AgHBs'),
('VDRL'),
('FT3'),
('FT4'),
('PSA'),
('Ogólne badanie moczu'),
('Ilościowe oznaczanie białka'),
('Ilościowe oznaczanie glukozy'),
('Ilościowe oznaczanie wapnia'),
('Ilościowe oznaczanie amylazy'),
('Badanie ogólne'),
('Pasożyty'),
('Krew utajona – metodą immunochemiczną'),
('Wskaźnik protrombinowy (INR)'),
('Czas kaolinowo-kefalinowy (APPT)'),
('Fibrynogen'),
('Posiew moczu z antybiogramem'),
('Posiew wymazu z gardła z antybiogramem'),
('Posiew kału w kierunku pałeczek Salmonella i Shigella'),
('Test antygenowy SARS-CoV-2 uzyskiwany za pomocą Systemu Dystrybucji Szczepionek (SDS)'),
('Badanie elektrokardiograficzne (EKG) w spoczynku'),
('USG tarczycy i przytarczyc'),
('USG ślinianek'),
('USG nerek, moczowodów, pęcherza moczowego'),
('USG brzucha i przestrzeni zaotrzewnowej, w tym wstępnej oceny gruczołu krokowego'),
('USG obwodowych węzłów chłonnych'),
('Zdjęcie klatki piersiowej w projekcji AP i bocznej'),
('Zdjęcie czaszki'),
('Zdjęcie zatok'),
('Zdjęcie przeglądowe jamy brzusznej'),
('Ferrytyna'),
('Witamina B12'),
('Kwas foliowy'),
('Anty CCP'),
('CRP szybki test ilościowy (populacja do ukończenia 6. roku życia)'),
('Przeciwciała anty-HCV'),
('Immunoglobuliny E całkowite (IgE)');

INSERT INTO choroba (nazwa, opis, czy_przewlekla, czy_zakazna) VALUES
('Nadciśnienie tętnicze', 'Przewlekła choroba układu krążenia charakteryzująca się podwyższonym ciśnieniem krwi w tętnicach', true, false),
('Cukrzyca typu 2', 'Zaburzenie metaboliczne charakteryzujące się podwyższonym poziomem glukozy we krwi', true, false),
('Astma oskrzelowa', 'Przewlekła choroba zapalna dróg oddechowych powodująca napady duszności', true, false),
('Przewlekła obturacyjna choroba płuc (POChP)', 'Progresywna choroba płuc charakteryzująca się ograniczeniem przepływu powietrza', true, false),
('Choroba wieńcowa', 'Choroba serca spowodowana zwężeniem lub niedrożnością tętnic wieńcowych', true, false),
('Depresja', 'Zaburzenie nastroju charakteryzujące się uporczywym smutkiem i utratą zainteresowania', true, false),
('Reumatoidalne zapalenie stawów', 'Przewlekła choroba autoimmunologiczna dotykająca głównie stawy', true, false),
('Osteoporoza', 'Choroba kości charakteryzująca się zmniejszeniem gęstości mineralnej kości', true, false),
('Alergia sezonowa', 'Reakcja alergiczna występująca w określonych porach roku, najczęściej na pyłki', true, false),
('Nadczynność tarczycy', 'Zaburzenie endokrynologiczne charakteryzujące się nadmierną produkcją hormonów tarczycy', false, false),
('Zapalenie stawów zwyrodnieniowe', 'Degeneracyjna choroba stawów prowadząca do uszkodzenia chrząstki stawowej', true, false),
('Niedokrwistość', 'Stan charakteryzujący się zmniejszoną liczbą krwinek czerwonych lub obniżonym poziomem hemoglobiny', false, false),
('Hipercholesterolemia', 'Podwyższony poziom cholesterolu we krwi zwiększający ryzyko chorób serca', true, false),
('Otyłość', 'Stan charakteryzujący się nadmierną masą ciała w stosunku do wzrostu', true, false),
('Zaburzenia trawienia', 'Problemy z prawidłowym trawieniem i wchłanianiem pokarmów', false, false),
('Migrena', 'Rodzaj bólu głowy charakteryzujący się silnym, pulsującym bólem', true, false),
('Bezsenność', 'Zaburzenie snu charakteryzujące się trudnościami z zasypianiem lub utrzymaniem snu', true, false),
('Zapalenie nerek', 'Proces zapalny dotykający nerki i ich struktury', false, true),
('Żylaki', 'Chorobowe poszerzenie i wydłużenie żył powierzchownych', true, false),
('Zapalenie pęcherzyka żółciowego', 'Proces zapalny dotykający pęcherzyk żółciowy', false, false),
('Grypa', 'Ostra choroba wirusowa układu oddechowego', false, true),
('Ospałość', 'Stan charakteryzujący się nadmierną sennością i zmęczeniem', false, false),
('Zapalenie płuc', 'Ostry proces zapalny dotykający pęcherzyki płucne', false, true),
('Zapalenie gardła', 'Proces zapalny błony śluzowej gardła', false, true),
('Zapalenie pęcherzyka moczowego', 'Infekcja bakteryjna dolnych dróg moczowych', false, true),
('Opryszczka zwykła', 'Wirusowa infekcja skóry powodowana przez wirus HSV', false, true),
('Bielmo', 'Zmętnienie rogówki oka prowadzące do pogorszenia widzenia', false, false),
('Zapalenie spojówek', 'Proces zapalny błony śluzowej pokrywającej powierzchnię oka', false, true),
('Nudności i wymioty', 'Zespół objawów związanych z zaburzeniami układu pokarmowego', false, false),
('Zaparcie', 'Zaburzenie czynności jelit charakteryzujące się rzadkim wypróżnianiem', false, false),
('Biegunka', 'Częste, luźne lub wodne wypróżnienia', false, true),
('Niedobór witaminy D', 'Stan niedoboru witaminy D w organizmie wpływający na kości i układ immunologiczny', true, false),
('Anemii niedoborowej żelaza', 'Rodzaj niedokrwistości spowodowany niedoborem żelaza w organizmie', true, false),
('Zapalenie wątroby typu B', 'Wirusowe zapalenie wątroby powodowane przez wirus HBV', false, true),
('Zapalenie wątroby typu C', 'Wirusowe zapalenie wątroby powodowane przez wirus HCV', false, true),
('HIV/AIDS', 'Choroba wywoływana przez wirus HIV atakujący układ immunologiczny', true, true),
('Gruźlica', 'Choroba zakaźna powodowana przez prątek gruźlicy', true, true),
('Tężec', 'Ostra choroba bakteryjna charakteryzująca się skurczami mięśni', false, true),
('Różyczka', 'Ostra choroba wirusowa charakteryzująca się wysypką i gorączką', false, true),
('Odra', 'Wysoce zakaźna choroba wirusowa charakteryzująca się charakterystyczną wysypką', false, true);

INSERT INTO symptom (nazwa) VALUES
('Ból głowy'),
('Gorączka'),
('Kaszel'),
('Duszność'),
('Zmęczenie'),
('Ból brzucha'),
('Nudności'),
('Wymioty'),
('Biegunka'),
('Zaparcie'),
('Ból w klatce piersiowej'),
('Ból stawów'),
('Ból mięśni'),
('Katar'),
('Ból gardła'),
('Chrypka'),
('Obrzęk'),
('Wysypka'),
('Świąd skóry'),
('Zawroty głowy'),
('Bezsenność');

INSERT INTO choroba_symptom (choroba_id, symptom_id) VALUES
(1, 1),
(1, 4),
(2, 5),
(2, 6),
(3, 3),
(3, 4),
(4, 3),
(4, 4),
(5, 11),
(5, 1),
(6, 1),
(6, 5),
(7, 11),
(7, 12),
(8, 13),
(8, 14),
(9, 18),
(9, 19),
(10, 1),
(10, 20);