set search_path TO przychodnia;

INSERT INTO specjalizacja (nazwa) VALUES
('Kardiologia'),
('Dermatologia'),
('Pediatria'),
('Neurologia'),
('Ortopedia'),
('Alergologia'),
('Anestezjologia i intensywna terapia'),
('Angiologia'),
('Audiologia i foniatria'),
('Balneologia i medycyna fizykalna'),
('Chirurgia dziecięca'),
('Chirurgia klatki piersiowej'),
('Chirurgia naczyniowa'),
('Chirurgia ogólna'),
('Chirurgia onkologiczna'),
('Chirurgia plastyczna'),
('Chirurgia szczękowo-twarzowa'),
('Choroby płuc'),
('Choroby płuc dzieci'),
('Choroby wewnętrzne'),
('Choroby zakaźne'),
('Dermatologia i wenerologia'),
('Diabetologia'),
('Diagnostyka laboratoryjna'),
('Endokrynologia'),
('Endokrynologia ginekologiczna i rozrodczość'),
('Endokrynologia i diabetologia dziecięca'),
('Epidemiologia'),
('Farmakologia kliniczna'),
('Gastroenterologia'),
('Gastroenterologia dziecięca'),
('Genetyka kliniczna'),
('Geriatria'),
('Ginekologia onkologiczna'),
('Hematologia'),
('Hipertensjologia'),
('Immunologia kliniczna'),
('Intensywna terapia'),
('Kardiochirurgia'),
('Kardiologia dziecięca'),
('Medycyna lotnicza'),
('Medycyna morska i tropikalna'),
('Medycyna nuklearna'),
('Medycyna paliatywna'),
('Medycyna pracy'),
('Medycyna ratunkowa'),
('Medycyna rodzinna'),
('Medycyna sądowa'),
('Medycyna sportowa'),
('Mikrobiologia lekarska'),
('Nefrologia'),
('Nefrologia dziecięca'),
('Neonatologia'),
('Neurochirurgia'),
('Neurologia dziecięca'),
('Neuropatologia'),
('Okulistyka'),
('Onkologia i hematologia dziecięca'),
('Onkologia kliniczna'),
('Ortopedia i traumatologia narządu ruchu'),
('Otorynolaryngologia'),
('Otorynolaryngologia dziecięca'),
('Patomorfologia'),
('Pediatria metaboliczna'),
('Perinatologia'),
('Położnictwo i ginekologia'),
('Psychiatria'),
('Psychiatria dzieci i młodzieży'),
('Radiologia i diagnostyka obrazowa'),
('Radioterapia onkologiczna'),
('Rehabilitacja medyczna'),
('Reumatologia'),
('Seksuologia'),
('Toksykologia kliniczna'),
('Transfuzjologia kliniczna'),
('Transplantologia kliniczna'),
('Urologia'),
('Urologia dziecięca'),
('Zdrowie publiczne'),
('Chirurgia stomatologiczna'),
('Ortodoncja'),
('Periodontologia'),
('Protetyka stomatologiczna'),
('Stomatologia dziecięca'),
('Stomatologia zachowawcza z endodoncją');

INSERT INTO lek (nazwa, substancja_czynna) VALUES
('Apap', 'Paracetamol'),
('Panadol', 'Paracetamol'),
('Tylenol', 'Paracetamol'),
('Ibupietas', 'Ibuprofen'),
('Ibuprom', 'Ibuprofen'),
('Nurofen', 'Ibuprofen'),
('Aspirin', 'Kwas acetylosalicylowy'),
('Acard', 'Kwas acetylosalicylowy'),
('Polopiryna', 'Metamizol'),
('Dipiryna', 'Metamizol'),
('Afobazol', 'Afobazol'),
('Phenibut', 'Fenibut'),
('Amoxyclav', 'Amoksycylina + Kwas klawulanowy'),
('Augmentin', 'Amoksycylina + Kwas klawulanowy'),
('Ciprofloxacin', 'Cyprofloksacyna'),
('Cipronex', 'Cyprofloksacyna'),
('Omeprazol', 'Omeprazol'),
('Gastrozol', 'Omeprazol'),
('Metformin', 'Metformina'),
('Glucophage', 'Metformina');

INSERT INTO alergia (nazwa) VALUES
('Pyłki roślin'),
('Kurz domowy'),
('Roztocza kurzu domowego'),
('Sierść zwierząt'),
('Lateks'),
('Orzechy'),
('Jaja'),
('Mleko'),
('Ryby'),
('Skorupiaki'),
('Leszczyna'),
('Olcha'),
('Wiąz'),
('Buk'),
('Brzoza'),
('Topola'),
('Dąb'),
('Wierzba'),
('Jesion'),
('Grab'),
('Bez czarny'),
('Lipa drobnolistna'),
('Trawy'),
('Babka lancetowata'),
('Pokrzywa'),
('Komosa'),
('Szczaw'),
('Bylica'),
('Zarodniki pleśni'),
('Ziarno sezamu'),
('Ryby i inne owoce morza'),
('Białko jaj'),
('Soja'),
('Rośliny strączkowe'),
('Kukurydza'),
('Zboża (gluten)'),
('Czekolada'),
('Owoce cytrusowe'),
('Miód'),
('Orzeszki ziemne'),
('Migdały'),
('Pistacje'),
('Nasiona słonecznika'),
('Nasiona sezamu'),
('Cebula'),
('Czosnek'),
('Zioła przyprawowe'),
('Przyprawy'),
('Roztocze'),
('Konserwanty'),
('Kosmetyki'),
('Jad pszczół');

INSERT INTO badanie (nazwa) VALUES
('Morfologia krwi'),
('Badanie moczu'),
('RTG klatki piersiowej'),
('EKG'),
('USG jamy brzusznej'),
('Lipidogram'),
('Glukoza na czczo'),
('Testy alergiczne'),
('Badanie poziomu hormonów tarczycy'),
('Kolonoskopia'),
('Morfologia krwi obwodowej z płytkami krwi'),
('Morfologia krwi obwodowej z wzorem odsetkowym i płytkami krwi'),
('Retikulocyty'),
('Odczyn opadania krwinek czerwonych (OB)'),
('Sód'),
('Potas'),
('Wapń zjonizowany'),
('Żelazo'),
('Żelazo – całkowita zdolność wiązania (TIBC)'),
('Stężenie transferryny'),
('Stężenie hemoglobiny glikowanej (HbAlc)'),
('Mocznik'),
('Kreatynina'),
('Glukoza'),
('Test obciążenia glukozą'),
('Białko całkowite'),
('Proteinogram'),
('Albumina'),
('Białko C-reaktywne (CRP)'),
('Kwas moczowy'),
('Cholesterol całkowity'),
('Cholesterol-HDL'),
('Cholesterol-LDL'),
('Trójglicerydy (TG)'),
('Bilirubina całkowita'),
('Bilirubina bezpośrednia'),
('Fosfataza alkaliczna (ALP)'),
('Aminotransferaza asparaginianowa (AST)'),
('Aminotransferaza alaninowa (ALT)'),
('Gammaglutamylotranspeptydaza (GGTP)'),
('Amylaza'),
('Kinaza kreatynowa (CK)'),
('Fosfataza kwaśna całkowita (ACP)'),
('Czynnik reumatoidalny (RF)'),
('Miano antystreptolizyn O (ASO)'),
('Hormon tyreotropowy (TSH)'),
('Antygen HBs-AgHBs'),
('VDRL'),
('FT3'),
('FT4'),
('PSA'),
('Ogólne badanie moczu'),
('Ilościowe oznaczanie białka'),
('Ilościowe oznaczanie glukozy'),
('Ilościowe oznaczanie wapnia'),
('Ilościowe oznaczanie amylazy'),
('Badanie ogólne'),
('Pasożyty'),
('Krew utajona – metodą immunochemiczną'),
('Wskaźnik protrombinowy (INR)'),
('Czas kaolinowo-kefalinowy (APPT)'),
('Fibrynogen'),
('Posiew moczu z antybiogramem'),
('Posiew wymazu z gardła z antybiogramem'),
('Posiew kału w kierunku pałeczek Salmonella i Shigella'),
('Test antygenowy SARS-CoV-2 uzyskiwany za pomocą Systemu Dystrybucji Szczepionek (SDS)'),
('Badanie elektrokardiograficzne (EKG) w spoczynku'),
('USG tarczycy i przytarczyc'),
('USG ślinianek'),
('USG nerek, moczowodów, pęcherza moczowego'),
('USG brzucha i przestrzeni zaotrzewnowej, w tym wstępnej oceny gruczołu krokowego'),
('USG obwodowych węzłów chłonnych'),
('Zdjęcie klatki piersiowej w projekcji AP i bocznej'),
('Zdjęcie czaszki'),
('Zdjęcie zatok'),
('Zdjęcie przeglądowe jamy brzusznej'),
('Ferrytyna'),
('Witamina B12'),
('Kwas foliowy'),
('Anty CCP'),
('CRP szybki test ilościowy (populacja do ukończenia 6. roku życia)'),
('Przeciwciała anty-HCV'),
('Immunoglobuliny E całkowite (IgE)');

INSERT INTO choroba (nazwa) VALUES
('Nadciśnienie tętnicze'),
('Cukrzyca typu 2'),
('Astma oskrzelowa'),
('Przewlekła obturacyjna choroba płuc (POChP)'),
('Choroba wieńcowa'),
('Depresja'),
('Reumatoidalne zapalenie stawów'),
('Osteoporoza'),
('Alergia sezonowa'),
('Nadczynność tarczycy'),
('Zapalenie stawów zwyrodnieniowe'),
('Niedokrwistość'),
('Hipercholesterolemia'),
('Otyłość'),
('Zaburzenia trawienia'),
('Migrena'),
('Bezsenność'),
('Zapalenie nerek'),
('Żylaki'),
('Zapalenie pęcherzyka żółciowego'),
('Grypa'),
('Ospałość'),
('Zapalenie płuc'),
('Zapalenie gardła'),
('Zapalenie pęcherzyka moczowego'),
('Opryszczka zwykła'),
('Bielmo'),
('Zapalenie spojówek'),
('Nudności i wymioty'),
('Zaparcie'),
('Biegunka'),
('Niedobór witaminy D'),
('Anemii niedoborowej żelaza'),
('Zapalenie wątroby typu B'),
('Zapalenie wątroby typu C'),
('HIV/AIDS'),
('Gruźlica'),
('Tężec'),
('Różyczka'),
('Odra');

INSERT INTO symptom (nazwa) VALUES
('Ból głowy'),
('Gorączka'),
('Kaszel'),
('Duszność'),
('Zmęczenie'),
('Ból brzucha'),
('Nudności'),
('Wymioty'),
('Biegunka'),
('Zaparcie'),
('Ból w klatce piersiowej'),
('Ból stawów'),
('Ból mięśni'),
('Katar'),
('Ból gardła'),
('Chrypka'),
('Obrzęk'),
('Wysypka'),
('Świąd skóry'),
('Zawroty głowy'),
('Bezsenność');

INSERT INTO choroba_symptom (choroba_id, symptom_id) VALUES
(1, 1),
(1, 4),
(2, 5),
(2, 6),
(3, 3),
(3, 4),
(4, 3),
(4, 4),
(5, 11),
(5, 1),
(6, 1),
(6, 5),
(7, 11),
(7, 12),
(8, 13),
(8, 14),
(9, 18),
(9, 19),
(10, 1),
(10, 20);